dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include(('df_user.urls','user'),namespace='user')),  #namespace格式必须是这样的
    url(r'^tinymce/', include('tinymce.urls')), #富文本编辑器配置
    url(r'^',include('df_goods.urls')),
    url(r'^cart/',include(('df_cart.urls','cart'),namespace='cart')),
    url(r'^order/',include(('df_order.urls','df_order'),namespace='df_order')),
    # url(r'^search/', include('haystack.urls')),  #全文检索,注释了是为了在df_goods/urls定义url使用上下文全文检索
]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.user_cart),
    url(r'^add(\d+)_(\d+)/$',views.add),
    url(r'^edit(\d+)_(\d+)/$',views.edit),
    url(r'^delete(\d+)/$',views.delete),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    url(r'^register_exit/$',views.register_exit,name='register_exit'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_handle/$',views.login_handle,name='login_handle'),
    url(r'^logout/$',views.login_handle,name='logout'),
    # url(r'^login_handle/$',views.login_handle1),
    # url(r'^user_exit/$',views.user_exit),
    # url(r'^upwd_exit/$',views.upwd_exit),
    url(r'^info/$',views.info,name='info'),
    url(r'^order/(\d+)$',views.order,name='order'),
    url(r'^site/$',views.site,name='site'),
]

dailyfresh/df_order/models.py
from django.db import models
from df_goods.models import *
from df_cart.models import *

# Create your models here.

class OrderInfo(models.Model):  # 大订单
    oid=models.CharField(max_length=20,primary_key=True)  #大订单号
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE)  #订单用户
    odate=models.DateTimeField(auto_now=True)  #时间
    oIsplay=models.BooleanField(default=False)  #是否支付
    ototal=models.DecimalField(max_digits=6,decimal_places=2)  # 虽然订单总价可以由多个商品的单价以及数量求得，但是由于用户订单的总价的大量使用，忽略total的冗余度
    oaddress=models.CharField(max_length=150)

# 无法实现：真实支付，物流信息
class OrderDetailInfo(models.Model):    # 大订单中的具体某一商品订单
    goods=models.ForeignKey(GoodsInfo,on_delete=models.CASCADE)   # 关联商品信息
    order=models.ForeignKey(OrderInfo,on_delete=models.CASCADE)   #订单
    price=models.DecimalField(max_digits=6,decimal_places=2)
    count=models.IntegerField()

dailyfresh/df_user/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    uname=models.CharField(max_length=20)
    upwd=models.CharField(max_length=40)
    uemail=models.CharField(max_length=30)
    ushou=models.CharField(max_length=20,default='')
    uadress=models.CharField(max_length=100,default='')
    upostal=models.CharField(max_length=6,default='')
    uphone=models.CharField(max_length=11,default='')
    #default和blank是python层面的约束，不影响数据库表结构

dailyfresh/df_user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from .models import *
import hashlib
from . import user_decorator
from df_goods.models import *
from df_cart.models import *
from df_order.models import *
from django.core.paginator import Paginator

#-----------------------注册------------------------
def register(request):
    return render(request,'df_user/register.html',{'title':'注册'})

def register_handle(request):
    #接收用户输入
    post=request.POST
    uname=post.get('user_name')
    upwd=post.get('pwd')
    upwd1=post.get('cpwd')
    uemail=post.get('email')
    #判断两次密码
    if upwd!=upwd1:
        return redirect('/user/register')
    #密码加密
    m=hashlib.md5()
    m.update(upwd.encode('utf-8'))
    mpwd=m.hexdigest()
    #创建对象,保存数据至数据库
    user=UserInfo()
    user.uname=uname
    user.upwd=mpwd
    user.uemail=uemail
    user.save()
    #注册成功，转到登录页面
    return redirect('/user/login')

def register_exit(requset):   #获取注册页用户名输入框的值的数量
    uname=requset.GET.get('uname')
    count=UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count':count})


#-----------------------登录------------------------
def login(request):
    uname=request.COOKIES.get('uname')
    context={'title':'用户登录','error_name':0,'error_pwd':0,'uname':uname}
    # return render(request,'df_user/login1.html',context)
    return render(request,'df_user/login.html',context)


###########方法一：没有利用ajax提交表单
def login_handle(request):
    #接受请求信息
    post=request.POST
    uname=post.get('username')
    upwd=post.get('pwd')
    jizhu=post.get('jizhu',0)  #没找到jizhu的值，则默认返回0
    #根据用户名查询对象
    users=UserInfo.objects.filter(uname=uname)  #返回的是个列表[]
    #判断：如果未查到则用户名错，如果查到则判断用户名是否正确，正确则转到用户中心
    if len(users)==1:
        m = hashlib.md5()
        m.update(upwd.encode('utf-8'))
        if m.hexdigest()==users[0].upwd:
            url=request.COOKIES.get('url','/')  #获取相关页面登录时cookies存储的路径url。详见user_decorator.login模块，为了从哪个页面进就从哪个页面出
            red=HttpResponseRedirect(url)
            #记住用户名
            if jizhu!=0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname','',max_age=-1)  # 设置过期cookie时间，max_age=-1立刻过期
            request.session['user_id']=users[0].id
            request.session['user_name']=uname
            return red     #用户名和密码正确，重定向到用户中心
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname,'upwd':upwd}
            return render(request, 'df_user/login.html', context)
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'df_user/login.html', context)


###########方法二：花了好长时间，写了下面这么多代码。只是自己做练习写的。就用方法一挺好，代码简洁
def login_handle1(request):
    # 接受请求信息
    post = request.POST
    uname = post.get('username')
    jizhu = post.get('jizhu', 0)  # 没找到jizhu的值，则默认返回0
    # 根据用户名查询对象
    users = UserInfo.objects.filter(uname=uname)  # 返回的是个列表[]
    red=HttpResponseRedirect('/user/info')
    if jizhu != 0:
        red.set_cookie('uname', uname)
    else:
        red.set_cookie('uname', '', max_age=-1)  # max_age=-1马上过期
    request.session['user_id'] = users[0].id
    request.session['user_name'] = uname
    return red

def user_exit(requset):     #这里除了用$.get()方法传递数据，还可以用$.post()方式传递数据，待研究
    uname = requset.GET.get('uname') #获取页面填写时的用户名
    # print(uname)
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})

def upwd_exit(requset):
    uname = requset.GET.get('uname')
    upwd=requset.GET.get('upwd')  #获取页面填写时写的密码
    print(upwd)
    m = hashlib.md5()
    m.update(upwd.encode('utf-8'))
    upwd1=m.hexdigest()
    user = UserInfo.objects.filter(uname=uname)  #返回的是个列表[]
    print(user)
    pwd=user[0].upwd
    if upwd1==pwd:
        count=1
    else:
        count=0
    return JsonResponse({'count': count})


#-----------------------用户中心------------------------
@user_decorator.login   #装饰器判断用户是否登录
def info(requset):
    uemail=UserInfo.objects.get(id=requset.session['user_id']).uemail

    # #--------最近浏览，关联见def_goods/views.detail模块
    goods_ids=requset.COOKIES.get('goods_id','1')   #####这里如果没有浏览记录goods_id，不给一个默认值的话会报错。有时间可以研究下怎么处理这种情况####
    # print(goods_ids)
    goods_ids1=goods_ids.split(',')
    # GoodsInfo.objects.filter(id__in=goods_ids)  #这样得到的数据没有按添加顺序排序，而是按id排序的
    goods_list=[]

    for goods_id in goods_ids1:
        goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    print(goods_list)

    context={'title':'用户中心',
             'page_name': 1,    #page_name用处，见base.html文件{% if page_name == 1 %}语句
             'uemail':uemail,
             'uname':requset.session['user_name'],
             'goods_list':goods_list
             }
    return render(requset,'df_user/user_center_info.html',context)


@user_decorator.login
def order(request,index):
    user_id=request.session['user_id']
    orders_list=OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    # print(orders_list)
    paginator=Paginator(orders_list,2)
    page=paginator.page(int(index))
    context = {
        'title': "用户中心",
        'page_name': 1,
        'page':page,
        'paginator':paginator,
        # 'orders_list':orders_list
    }
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login   #装饰器判断用户是否登录
def site(requset):
    user=UserInfo.objects.get(id=requset.session['user_id'])
    if requset.method=='POST':
        post=requset.POST
        user.ushou=post.get('ushou')
        user.uadress=post.get('uadress')
        user.upostal=post.get('upostal')
        user.uphone=post.get('uphone')
        user.save()
    context={'user':user,'title':'用户中心','page_name': 1}
    return render(requset,'df_user/user_center_site.html',context)


#-----------------------登出------------------------
def logout(request):
    request.session.flush()    #删除当前的会话数据并删除会话的Cookie
    return redirect("/")    #？？？？这里为什么不能重定向到首页，我表示很困惑？？？？？？

dailyfresh/templates/df_user/login.html
{% extends 'base_foot.html' %}

{% block head %}
<script>
	$(function(){
		name_error=false;
		pwd_error=false;

		//判断用户名和密码是否正确
		if({{error_name}}==1){
			$('.name_input').next().html('用户名错误').show()
		}

		if({{error_pwd}}==1){
			$('.pass_input').next().html('密码错误').show()
		}

		//判断用户名和密码是否输入
		$('.name_input').blur(function(){
			check_username();
		})
		$('.name_input').click(function(){
			$(this).next().hide()
		})

		$('.pass_input').blur(function(){
			check_pwd();
		})
		$('.pass_input').click(function(){
			$(this).next().hide()
		})

		//检查用户名
		function check_username(){
			var user=$('.name_input').val()
				if(user==''){
					$('.user_error').html('请输入用户名').show();
					name_error=true;
					return
				}
				else{
					$('.user_error').hide();
					name_error=false;
				}
		}

		//检查密码
		function check_pwd(){
			var pwd=$('.pass_input').val()
				if(pwd==''){
					$('.pwd_error').html('请输入密码').show();
					pwd_error=true;
					return
				}
				else{
					$('.pwd_error').hide();
					pwd_error=false;
				}
		}

		//表单提交校验
		$('.form_input').submit(function(){
			check_username();
			check_pwd();

			if(name_error==false && pwd_error==false){
				return true;
			}
			else{
				return false;
			}
		})
	})
</script>
{% endblock head %}

{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'user:login_handle' %}" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

dailyfresh/templates/df_user/login1.html
{% extends 'base_foot.html' %}

{% block head %}
<script>
	$(function(){
		name_error=false;
		pwd_error=false;

		//判断用户名和密码是否输入
		$('.name_input').blur(function(){
			check_username();
		})
		$('.name_input').click(function(){
			$(this).next().hide()
		})

		$('.pass_input').blur(function(){
			check_pwd();
		})
		$('.pass_input').click(function(){
			$(this).next().hide()
		})

		//检查用户名
		function check_username(){
			var user=$('.name_input').val()
				if(user==''){
					$('.user_error').html('请输入用户名').show();
					name_error=true;
					return
				}
				else{
					$.get('/user/user_exit/?uname='+user,function(data){
						if(data.count==1){
							$('.user_error').hide();
							name_error=false;
						}
						else{
							$('.user_error').html('用户名错误').show();
							name_error=true;
						}
					})
				}
		}

		//检查密码
		function check_pwd(){
			var pwd=$('.pass_input').val()
				if(pwd==''){
					$('.pwd_error').html('请输入密码').show();
					pwd_error=true;
					return
				}
				else{
					$.get('/user/upwd_exit/?uname='+$('.name_input').val()+'&'+'upwd='+pwd,function(data){
						if(data.count==1){
							$('.pwd_error').hide();
							name_error=false;
						}
						else{
							$('.pwd_error').html('密码错误').show();
							name_error=true;
						}
					})
				}
		}

		//表单提交校验
		$('.form_input').submit(function(){
			check_username();
			check_pwd();

			if(name_error==false && pwd_error==false){
				return true;
			}
			else{
				return false;
			}
		})
	})
</script>
{% endblock head %}

{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

dailyfresh/templates/df_user/register.html
{% extends 'base_foot.html' %}

{% block head %}
<script type="text/javascript" src="/static/js/register1.js"></script>
{% endblock head %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'user:register_handle' %}" method="post">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

dailyfresh/templates/df_user/user_center_info.html
{% extends 'base.html' %}

{% block content %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'user:site' %}">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{uname}}</li>
							<li><span>联系邮箱：</span>{{uemail}}</li>
							<!--<li><span>联系地址：</span>北京市昌平区</li>	-->
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
						<!--<li>-->
							<!--<a href="detail.html"><img src="/static/images/goods/goods003.jpg"></a>-->
							<!--<h4><a href="detail.html">大兴大棚草莓</a></h4>-->
							<!--<div class="operate">-->
								<!--<span class="prize">￥16.80</span>-->
								<!--<span class="unit">16.80/500g</span>-->
								<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
							<!--</div>-->
						<!--</li>-->
		<!---->
						<!--<li>-->
							<!--<a href="#"><img src="/static/images/goods/goods004.jpg"></a>-->
							<!--<h4><a href="#">吐鲁番梨光杏</a></h4>-->
							<!--<div class="operate">-->
								<!--<span class="prize">￥5.50</span>-->
								<!--<span class="unit">5.50/500g</span>-->
								<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
							<!--</div>-->
						<!--</li>-->
		<!---->
						<!--<li>-->
							<!--<a href="#"><img src="/static/images/goods/goods005.jpg"></a>-->
							<!--<h4><a href="#">黄肉桃</a></h4>-->
							<!--<div class="operate">-->
								<!--<span class="prize">￥10.00</span>-->
								<!--<span class="unit">10.00/500g</span>-->
								<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
							<!--</div>-->
						<!--</li>-->
		<!---->
						<!--<li>-->
							<!--<a href="#"><img src="/static/images/goods/goods006.jpg"></a>-->
							<!--<h4><a href="#">进口西梅</a></h4>-->
							<!--<div class="operate">-->
								<!--<span class="prize">￥28.80</span>-->
								<!--<span class="unit">28.8/500g</span>-->
								<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
							<!--</div>-->
						<!--</li>-->
		<!---->
						<!--<li>-->
							<!--<a href="#"><img src="/static/images/goods/goods007.jpg"></a>-->
							<!--<h4><a href="#">香梨</a></h4>-->
							<!--<div class="operate">-->
								<!--<span class="prize">￥6.45</span>-->
								<!--<span class="unit">6.45/500g</span>-->
								<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
							<!--</div>-->
						<!--</li>-->


						<!--最近浏览-->
						{% for goods in goods_list %}
						<li>
							<a href="#"><img src="/static/{{goods.gpic}}"></a>
							<h4><a href="#">{{goods.gtitle}}</a></h4>
							<div class="operate">
								<span class="prize">￥{{goods.gprice}}</span>
								<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
								<a href="#" class="add_goods" title="加入购物车"></a>
							</div>
						</li>
						{% endfor %}

					</ul>
		</div>
		</div>
</div>
{% endblock content %}

dailyfresh/templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block content %}
<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'user:info' %}">· 个人信息</a></li>
			<li><a href="{% url 'user:order' 1 %}" class="active">· 全部订单</a></li>
			<li><a href="{% url 'user:site' %}">· 收货地址</a></li>
		</ul>
	</div>

	<div class="right_content clearfix">
			<h3 class="common_title2">全部订单</h3>

		{% for orderinfo in page %}
			<ul class="order_list_th w978 clearfix">
				<li class="col01">{{orderinfo.odate|date}}</li>
				<li class="col02">订单号：{{orderinfo.oid}}</li>
				<li class="col02 stress">未支付</li>
			</ul>

			<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
							<!--<ul class="order_goods_list clearfix">-->
								<!--<li class="col01"><img src="/static/images/goods02.jpg"></li>-->
								<!--<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>-->
								<!--<li class="col03">1</li>-->
								<!--<li class="col04">11.80元</li>-->
							<!--</ul>-->

						    {% for order_detail in orderinfo.orderdetailinfo_set.all %}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="/static/images/goods02.jpg"></li>
								<li class="col02">{{order_detail.goods.gtitle}}<em class="good_price">{{order_detail.goods.gprice}}元/{{order_detail.goods.gunit}}</em></li>
								<li class="col03">{{order_detail.count}}件</li>
								<li class="col04"></li>
							</ul>
							{% endfor %}

						</td>
						<td width="15%">{{orderinfo.ototal}}元</td>
						<td width="15%">待付款</td>
						<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
					</tr>
				</tbody>
			</table>
		{% endfor %}

			<!--<ul class="order_list_th w978 clearfix">-->
				<!--<li class="col01">2016-8-21 17:36:24</li>-->
				<!--<li class="col02">订单号：56872934</li>-->
				<!--<li class="col02 stress">已支付</li>-->
			<!--</ul>-->
			<!--<table class="order_list_table w980">-->
				<!--<tbody>-->
					<!--<tr>-->
						<!--<td width="55%">-->
							<!--<ul class="order_goods_list clearfix">-->
								<!--<li class="col01"><img src="/static/images/goods02.jpg"></li>-->
								<!--<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>-->
								<!--<li class="col03">1</li>-->
								<!--<li class="col04">11.80元</li>-->
							<!--</ul>-->
							<!--<ul class="order_goods_list clearfix">-->
								<!--<li class="col01"><img src="/static/images/goods02.jpg"></li>-->
								<!--<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>-->
								<!--<li class="col03">1</li>-->
								<!--<li class="col04">11.80元</li>-->
							<!--</ul>-->
						<!--</td>-->
						<!--<td width="15%">33.60元</td>-->
						<!--<td width="15%">已付款</td>-->
						<!--<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>-->
					<!--</tr>-->
				<!--</tbody>-->
			<!--</table>-->

			<div class="pagenation">
				<!--<a href="#"><上一页</a>-->
				<!--<a href="#" class="active">1</a>-->
				<!--<a href="#">2</a>-->
				<!--<a href="#">3</a>-->
				<!--<a href="#">4</a>-->
				<!--<a href="#">5</a>-->
				<!--<a href="#">下一页></a>-->

				{% if page.has_previous %}
				<a href="{% url 'user:order' page.previous_page_number %}">上一页</a>
				{% endif %}

				{% for index in paginator.page_range %}
					{% if index == page.number %}
						<a href="{% url 'user:order' index %}" class="active">{{index}}</a>
					{% else %}
						<a href="{% url 'user:order' index %}">{{index}}</a>
					{% endif %}
				{% endfor %}

				{% if page.has_next %}
				<a href="{% url 'user:order' page.next_page_number  %}">下一页</a>
				{% endif %}
			</div>
	</div>
</div>

<script type="text/javascript">
	$(function(){
		$('.col04').each(function(){
			count=$(this).prev().text();
			price=$(this).prev().prev().find('.good_price').text();
			//alert(count)
			//alert(price)
			$(this).html(parseFloat(count,2)*parseFloat(price,2)+'元');
		})
	})
</script>

{% endblock content %}

dailyfresh/templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block content %}
<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'user:info' %}">· 个人信息</a></li>
			<li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
			<li><a href="{% url 'user:site' %}" class="active">· 收货地址</a></li>
		</ul>
	</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uadress}}（{{user.ushou}}收） {{user.uphone}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{user.ushou}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uadress" >{{user.uadress}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="upostal" value="{{user.upostal}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{user.uphone}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
</div>
{% endblock content %}