dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include(('df_user.urls','user'),namespace='user')),  #namespace格式必须是这样的
    url(r'^tinymce/', include('tinymce.urls')), #富文本编辑器配置
    url(r'^',include('df_goods.urls')),
    url(r'^cart/',include(('df_cart.urls','cart'),namespace='cart')),
    url(r'^order/',include(('df_order.urls','df_order'),namespace='df_order')),
    # url(r'^search/', include('haystack.urls')),  #全文检索,注释了是为了在df_goods/urls定义url使用上下文全文检索
]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.user_cart),
    url(r'^add(\d+)_(\d+)/$',views.add),
    url(r'^edit(\d+)_(\d+)/$',views.edit),
    url(r'^delete(\d+)/$',views.delete),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    url(r'^register_exit/$',views.register_exit,name='register_exit'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_handle/$',views.login_handle,name='login_handle'),
    url(r'^logout/$',views.login_handle,name='logout'),
    # url(r'^login_handle/$',views.login_handle1),
    # url(r'^user_exit/$',views.user_exit),
    # url(r'^upwd_exit/$',views.upwd_exit),
    url(r'^info/$',views.info,name='info'),
    url(r'^order/(\d+)$',views.order,name='order'),
    url(r'^site/$',views.site,name='site'),
]

dailyfresh/templates/base.html
{% extends 'base_foot.html' %}

{% block body %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.user_name|default:'' != '' %}   <!--default过滤器进行判断如果request.session.user_name不等于空字符串则用户登陆状态为true,也就是说当用户为已登陆状态时则显示用户名-->
				<div class="login_btn fl">
					欢迎您：<em>{{request.session.user_name}}</em>&nbsp;
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}

				<!--<div class="login_btn fl">-->
					<!--欢迎您：<em>张 山</em>-->
					<!--<a href="">退出</a>-->
				<!--</div>-->
				<!--<div class="login_btn fl">-->
					<!--<a href="login.html">登录</a>-->
					<!--<span>|</span>-->
					<!--<a href="register.html">注册</a>-->
				<!--</div>-->

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		{% if page_name == 1 %}
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{title}}</div>
		{% endif %}
		<div class="search_con fl">
			<form action="/search/"  method="get">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">   <!--自定义上下文，全文检索。action="/search/" 指向search.html文件，name="q" 固定写法-->
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		{% if guest_cart == 1 %}
		<div class="guest_cart fr">
			<a href="/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{cart_num}}</div>
		</div>
		{% endif %}
	</div>

{% block content %}{% endblock content %}

{% endblock body %}

dailyfresh/templates/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-{{title}}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	{% block head %}{% endblock head %}
</head>

<body>

{% block body %}{% endblock body %}

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>